title: "LH-DEV"
author: "LH-DEV"
description: "LH-DEV"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "tools.md", icon: address-card}
  - {file: "setupguide.md", icon: address-card}
  - {file: "testserver.md", icon: address-card}  
  - {file: "sourceedits.md", icon: address-card}
  - {file: "contact.md", icon: address-card}
  
external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "/contact/"}

bico:
  - {title: Bico, icon: bicon, url: ""}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/
